scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        min_x: -0.25
        max_x: 0.47
        min_y: -0.2325
        max_y: 0.2325
        min_z: -1.0
        max_z: 1.0