collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_raw"
    cmd_vel_out_topic: "cmd_vel"
    transform_tolerance: 0.5
    source_timeout: 5.0
    stop_pub_timeout: 2.0
    polygons: ["PolygonStop", "PolygonSlow"]
    PolygonStop:
      type: "polygon"
      points: [0.75, 0.28, 0.75, -0.28, -0.00, -0.28, -0.00, 0.28]
      action_type: "stop"
      max_points: 3
      # min_points: 4  # max_points: 3 for Humble
      visualize: True
      polygon_pub_topic: "polygon_stop"
    PolygonSlow:
      type: "polygon"
      points: [0.90, 0.38, 0.90, -0.38, -0.00, -0.38, -0.00, 0.38]
      action_type: "slowdown"
      max_points: 3
      # min_points: 4  # max_points: 3 for Humble
      slowdown_ratio: 0.5
      visualize: True
      polygon_pub_topic: "polygon_slowdown"
    observation_sources: ["scan"]
    scan:
      source_timeout: 0.2
      type: "scan"
      topic: "/scan"
      enabled: True
    # observation_sources: ["scan", "pointcloud"]
    # scan:
    #   source_timeout: 0.2
    #   type: "scan"
    #   topic: "/scan"
    #   enabled: True