### ekf config file ###
ekf_filter_node:
    ros__parameters:
        debug: false
        frequency: 50.0
        two_d_mode: false
        publish_acceleration: false
        publish_tf: true
        map_frame: map              # 如果未指定，默认为"map"
        odom_frame: odom            # 如果未指定，默认为"odom"
        base_link_frame: base_link  # 如果未指定，默认为"base_link"
        world_frame: odom           # 如果未指定，默认为odom_frame的值

        odom0: /base/odom
        odom0_config: [true,  true,  true,
                       false, false, false,
                       false, false, false,
                       false, false, true,
                       false, false, false]

        imu0: /base/imu
        imu0_config: [false, false, false,
                      true,  true,  true,
                      false, false, false,
                      false, false, false,
                      false, false, false]
