planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    planner_plugins: ['GridBased']
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner' 
      use_astar: True
      allow_unknown: True
      tolerance: 1.0
