planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    planner_plugins: ['GridBased']
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner' 
      use_astar: True
      allow_unknown: True
      tolerance: 1.0

global_costmap:
  global_costmap:
    ros__parameters:
      footprint_padding: 0.10
      footprint: "[ [0.45, 0.2325], [0.45, -0.2325], [-0.25, -0.2325], [-0.25, 0.2325] ]"
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: false
      # robot_radius: 0.45 # radius set and used, so no footprint points
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "denoise_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 0.1
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan 
        # observation_sources: scan pointcloud
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        combination_method: 1
        scan:
          topic: /scan
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: false
        # pointcloud:  
        #   topic: /camera/depth/points
        #   max_obstacle_height: 2.0
        #   min_obstacle_height: 0.0
        #   obstacle_max_range: 2.5
        #   obstacle_min_range: 0.0
        #   raytrace_max_range: 3.0
        #   raytrace_min_range: 0.0
        #   clearing: True
        #   marking: True
        #   data_type: "PointCloud2"
      denoise_layer:
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: true
        minimal_group_size: 2
        group_connectivity_type: 8
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.10
        cost_scaling_factor: 1.0
        inflate_unknown: false
        inflate_around_unknown: true
      always_send_full_costmap: True